<script>
  import { push } from "svelte-spa-router";
  import contractAddress from "../stores/contractAddress";
  import networkConfig from '../stores/networkConfig';

  const { isMainnet } = networkConfig;
  
  const contractList = ["rizon1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqcmfdak", "rizon1xr3rq8yvd7qplsw5yx90ftsr2zdhg4e9z60h5duusgxpv72hud3s5ux3n5"];
  
  function handleClick(id) {
      contractAddress.set(contractList[id]);
      push(`/contract/${contractList[id]}`);
  }
  
  </script>
  
  <h1 class="font-sans font-bold text-5xl my-10">Welcome to RIZON NFT Finder</h1>
  <p>You can find all NFTs on the RIZON network.</p>
  {#if $isMainnet === false}
  <p class="mb-5">They are some NFT collections are exist. Enjoy it!</p>
  <div class="flex gap-5 justify-center">
      <div class="card w-96 bg-base-100 shadow-xl">
          <figure class="px-10 pt-10">
            <img src="https://ipfs.io/ipfs/bafybeihznjgkq3r57uaclzvkzrfl2h4wztwopcqwdj5qnxiahc3i5mgbdq" alt="Flower" class="rounded-xl" />
          </figure>
          <div class="card-body items-center text-center">
            <h2 class="card-title">The Origin</h2>
            <p>This NFT is the first NFT on the RIZON network, created to demonstrate NFTs on the RIZON network.</p>
            <div class="card-actions">
              <button class="btn btn-primary" on:click="{() => handleClick(0)}">Show now!</button>
            </div>
          </div>
      </div>
      <div class="card w-96 bg-base-100 shadow-xl">
          <figure class="px-10 pt-10">
            <img src="https://ipfs.io/ipfs/bafybeigj2myyajqtmehxdouff7o7gk6e244sz6hgsx4zb7spg2zwd3kx5m/7.jpeg" alt="Monster" class="rounded-xl" />
          </figure>
          <div class="card-body items-center text-center">
            <h2 class="card-title">The Monsters</h2>
            <p>The first NFT collection on the RIZON network, "The monsters" series. All monsters are unique and generated by AI.</p>
            <div class="card-actions">
              <button class="btn btn-primary" on:click="{() => handleClick(1)}">Show now!</button>
            </div>
          </div>
      </div>
  </div>
  {/if}