<script>
import contractAddress from "../stores/contractAddress";

const contractList = ["rizon14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s5wv0ls", "rizon1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstmq6he"];

function handleClick(id) {
    contractAddress.set(contractList[id]);
}

</script>

<h1 class="font-sans font-bold text-5xl my-10">Welcome to RIZON NFT Finder</h1>
<p>Here you can find all NFTs on the RIZON network.</p>
<p class="mb-5">They are some NFT collections are exist. Enjoy it!</p>
<div class="flex gap-5 justify-center">
    <div class="card w-96 bg-base-100 shadow-xl">
        <figure class="px-10 pt-10">
          <img src="https://ipfs.io/ipfs/bafybeihznjgkq3r57uaclzvkzrfl2h4wztwopcqwdj5qnxiahc3i5mgbdq" alt="Flower" class="rounded-xl" />
        </figure>
        <div class="card-body items-center text-center">
          <h2 class="card-title">The Origin</h2>
          <p>This NFT is the first NFT on the RIZON network, created to demonstrate NFTs on the RIZON network.</p>
          <div class="card-actions">
            <button class="btn btn-primary" on:click="{() => handleClick(0)}">Show now!</button>
          </div>
        </div>
    </div>
    <div class="card w-96 bg-base-100 shadow-xl">
        <figure class="px-10 pt-10">
          <img src="https://ipfs.io/ipfs/bafybeigj2myyajqtmehxdouff7o7gk6e244sz6hgsx4zb7spg2zwd3kx5m/7.jpeg" alt="Monster" class="rounded-xl" />
        </figure>
        <div class="card-body items-center text-center">
          <h2 class="card-title">The Monsters</h2>
          <p>The first NFT collection on the RIZON network, "The monsters" series. All monsters are unique and generated by AI.</p>
          <div class="card-actions">
            <button class="btn btn-primary" on:click="{() => handleClick(1)}">Show now!</button>
          </div>
        </div>
    </div>
</div>